name: config_cat
description: A library for config cat
version: 0.0.1
author: Minsu Lee <amond@amond.net>
homepage: https://github.com/amondnet/config_cat.dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  quiver: '>=2.0.0 <3.0.0'
  logging: ^0.11.3+2
  dio: ^2.1.0
  json_annotation: ^2.0.0
  equatable: ^0.5.1
  synchronized: ^2.1.0+1
  # crypto: ^2.1.2

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  test: ^1.6.9
  mock_web_server: ^4.1.0
  fake_async: ^1.0.1



